StadiumTracker.WebMVC/Controllers/ParkController.cs
using Microsoft.AspNet.Identity;
using StadiumTracker.Models.ParkModels;
using StadiumTracker.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StadiumTracker.WebMVC.Controllers
{
    [Authorize]
    public class ParkController : Controller
    {
        // GET: Park
        public ActionResult Index()
        {
            var service = CreateParkService();
            return View(service.GetParks());
        }

        //Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ParkCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateParkService();

            if (service.CreatePark(model))
            {
                TempData["SaveResult"] = "New Park added";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Park could not be added");
            return View(model);
        }

        //Details
        public ActionResult Details(int id)
        {
            var service = CreateParkService();
            var model = (service.GetParkById(id));
            model.CurrentUser = Guid.Parse(User.Identity.GetUserId());
            return View(model);
        }

        //Edit
        public ActionResult Edit(int id)
        {
            var service = CreateParkService();
            var detail = service.GetParkById(id);
            var model =
                new ParkEdit
                {
                    ParkId = detail.ParkId,
                    ParkName = detail.ParkName,
                    CityName = detail.CityName
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ParkEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.ParkId != id)
            {
                ModelState.AddModelError("", "Ids are mistmatched.");
                return View(model);
            }

            var service = CreateParkService();

            if (service.UpdatePark(model))
            {
                TempData["SaveResult"] = "Park was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Park could not be updated.");
            return View(model);
        }

        //Delete
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var service = CreateParkService();
            return View(service.GetParkById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateParkService();
            service.DeletePark(id);
            TempData["SaveResult"] = "Park has been deleted.";
            return RedirectToAction("Index");
        }

        private ParkService CreateParkService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            return new ParkService(userId);
        }
    }
}

StadiumTracker.WebMVC/Controllers/VisitController.cs
using Microsoft.AspNet.Identity;
using StadiumTracker.Data;
using StadiumTracker.Models.VisitModels;
using StadiumTracker.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StadiumTracker.WebMVC.Controllers
{
    [Authorize]
    public class VisitController : Controller
    {
        public ActionResult Index()
        {
            var service = CreateVisitService();
            return View(service.GetVisits());
        }

        public ActionResult Create()
        {
            var service = CreateVisitService();
            var visitorService = new VisitorService(Guid.Parse(User.Identity.GetUserId()));

            var unsortedVisitorList = new SelectList(visitorService.GetVisitors(), "VisitorId", "FullName");
            var visitorList = unsortedVisitorList.OrderBy(o => o.Text);

            var unsortedParkList = new SelectList(service.GetOwnedList("Park"), "ParkId", "ParkName");
            var parkList = unsortedParkList.OrderBy(o => o.Text);

            var unsortedTeamList = new SelectList(service.GetOwnedList("Team"), "TeamId", "TeamName");
            var teamList = unsortedTeamList.OrderBy(o => o.Text);

            ViewBag.VisitorId = visitorList;
            ViewBag.ParkId = parkList;
            ViewBag.HomeTeamId = teamList;
            ViewBag.AwayTeamId = teamList;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VisitCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateVisitService();

            if (service.CreateVisit(model))
            {
                TempData["SaveResult"] = "New Visit Added";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Visit could not be added.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var service = CreateVisitService();
            return View(service.GetVisitById(id));
        }

        public ActionResult Edit(int id)
        {
            var service = CreateVisitService();

            var unsortedVisitorList = new SelectList(service.GetOwnedList("Visitor"), "VisitorId", "FullName");
            var visitorList = unsortedVisitorList.OrderBy(o => o.Text);

            var unsortedParkList = new SelectList(service.GetOwnedList("Park"), "ParkId", "ParkName");
            var parkList = unsortedParkList.OrderBy(o => o.Text);

            var unsortedTeamList = new SelectList(service.GetOwnedList("Team"), "TeamId", "TeamName");
            var teamList = unsortedTeamList.OrderBy(o => o.Text);

            ViewBag.VisitorId = visitorList;
            ViewBag.ParkId = parkList;
            ViewBag.HomeTeamId = teamList;
            ViewBag.AwayTeamId = teamList;

            var detail = service.GetVisitById(id);
            var model =
                new VisitEdit
                {
                    VisitId = detail.VisitId,
                    ParkName = detail.ParkName,
                    HomeTeamName = detail.HomeTeamName,
                    AwayTeamName = detail.AwayTeamName,
                    VisitorFirstName = detail.VisitorFirstName,
                    VisitorLastName = detail.VisitorLastName,
                    VisitDate = detail.VisitDate,
                    GotPin = detail.GotPin,
                    GotPhoto = detail.GotPhoto
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, VisitEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.VisitId != id)
            {
                ModelState.AddModelError("", "Ids are mismatched.");
                return View(model);
            }

            var service = CreateVisitService();

            if (service.UpdateVisit(model))
            {
                TempData["SaveResult"] = "Visit was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Visit could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var service = CreateVisitService();
            return View(service.GetVisitById(id));
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateVisitService();
            service.DeleteVisit(id);
            TempData["SaveResult"] = "Visit has been deleted.";
            return RedirectToAction("Index");
        }

        private VisitService CreateVisitService()
        {
            var ownerId = Guid.Parse(User.Identity.GetUserId());
            return new VisitService(ownerId);
        }
    }
}

StadiumTracker.WebMVC/Views/Shared/_CreateView.cshtml
@using StadiumTracker.WebMVC.Helpers

@{
    var name = Html.CurrentViewName();
    var controller = Html.ControllerName();
    if (name == "Index" && controller != "HomeController")
    {
        <p>
            @Html.ActionLink("Add New", "Create")
        </p>
    }
}

StadiumTracker.WebMVC/Views/Shared/_EditView.cshtml
@using StadiumTracker.WebMVC.Helpers

@{
    var name = Html.CurrentViewName();
    var controller = Html.ControllerName();
    if (name == "Details" && controller != "HomeController")
    {
        <p>
            @Html.ActionLink("Edit", "Edit", )
        </p>
    }
}

StadiumTracker.WebMVC/Views/Shared/_Layout.cshtml
@using StadiumTracker.WebMVC.Helpers
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Stadium Tracker</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Style.css">
</head>
<body>
    <div class="container body-container">
        <div id="belowNav">
            <div class="col-lg-2 col-md-2 fixed-right navbar-details">
                <div class="navbar-name">
                    @Html.ActionLink("Stadium Tracker", "Index", "Home")
                </div>
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @*<li>@Html.ActionLink("About", "Index", "Park")</li>*@
                        <li>@Html.ActionLink("Stadiums", "Index", "Park")</li>
                        <li>@Html.ActionLink("Teams", "Index", "Team")</li>
                        <li>@Html.ActionLink("Visits", "Index", "Visit")</li>
                        <li>@Html.ActionLink("People", "Index", "Visitor")</li>
                        <li><br /> </li>
                        <li><br /> </li>
                        <li>@Html.Partial("_CreateView")</li>
                        <li>@Html.Partial("_LeaguePartial")</li>
                    }
                </ul>
                <div class="row">
                    <div class="col-lg-2 col-md-2" id="footer">
                        @Html.Partial("_LoginPartial")
                        <footer>
                            <p>&copy; @DateTime.Now.Year Stadium Tracker</p>
                        </footer>
                    </div>
                </div>
            </div>
            <div class="col-lg-10 col-md-10 scroll-content">
                <div class="container body-content">
                    @RenderBody()
                </div>
            </div>

        </div>


    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StadiumTracker.WebMVC/Views/Shared/_LeaguePartial.cshtml
@using StadiumTracker.WebMVC.Helpers

@{
    var name = Html.CurrentViewName();
    var controller = Html.ControllerName();
    if (controller == "TeamController")
    {
        <p>
            @Html.ActionLink("View Leagues", "../League")
        </p>
    }
}